#!/bin/bash

MY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUYI_BUILDER_TAG="${RUYI_BUILDER_TAG:-ghcr.io/ruyisdk/ruyi-builder:ubuntu2004-20240127}"

ARCH="${ARCH:-amd64}"

die() {
	echo "$@" >&2
	exit 1
}

ensure_dir() {
	local path="$1"
	[[ -d "$path" ]] || mkdir "$path"
}

main() {
	local pkg="$1"

	ensure_dir "$MY_DIR/out"
	ensure_dir "$MY_DIR/work"

	# assume /tmp is tmpfs for now
	TMP_MEM_DIR="$(mktemp -d)"

	local docker_args=(
		--rm
		-ti
		-v "$MY_DIR/out":/out
		-v "$MY_DIR/work":/work
		-v "$MY_DIR/ruyi-build-llvm-inner":/usr/local/bin/ruyi-build-llvm-inner:ro
		-v "$TMP_MEM_DIR":/tmp/mem
	)

	if [[ -n $pkg ]]; then
		docker_args+=(
			-v "$pkg":/tmp/src.tar.xz:ro
		)
	fi

	docker_args+=(
		"${RUYI_BUILDER_TAG}"
		ruyi-build-llvm-inner
		"$ARCH"
	)

	docker run "${docker_args[@]}" || die "inner build pass failed"
}

main "$@"
