#!/bin/bash

MY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUYI_BUILDER_TAG="${RUYI_BUILDER_TAG:-ruyi-builder:ubuntu2004-20231202}"

die() {
	echo "$@" >&2
	exit 1
}

ensure_dir() {
	local path="$1"
	[[ -d "$path" ]] || mkdir "$path"
}

main() {
	local config="$1"

	ensure_dir "$MY_DIR/out"
	ensure_dir "$MY_DIR/prefix"
	ensure_dir "$MY_DIR/src"
	ensure_dir "$MY_DIR/work"

	local docker_args=(
		--rm
		-ti
		-v "$MY_DIR/out":/out
		-v "$MY_DIR/prefix":/opt/ruyi
		-v "$MY_DIR/src":/src
		-v "$MY_DIR/work":/work
		-v "$MY_DIR/ruyi-build-inner":/usr/local/bin/ruyi-build-inner:ro
		-v "$(realpath "$config")":/tmp/input.defconfig:ro
		"${RUYI_BUILDER_TAG}"
		ruyi-build-inner /tmp/input.defconfig
	)
	docker run "${docker_args[@]}" || die "inner build pass failed"
}

main "$@"
