#!/bin/bash

MY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUYI_BUILDER_TAG="${RUYI_BUILDER_TAG:-ruyi-builder:ubuntu2204-20231025}"

ensure_dir() {
	local path="$1"
	[[ -d "$path" ]] || mkdir "$path"
}

main() {
	local config="$1"

	ensure_dir "$MY_DIR/out"
	ensure_dir "$MY_DIR/src"
	ensure_dir "$MY_DIR/work"

	local docker_args=(
		--rm
		-ti
		"${RUYI_BUILDER_TAG}"
		-v "$MY_DIR/out":/out
		-v "$MY_DIR/src":/src
		-v "$MY_DIR/work":/work
		-v "$(realpath "$config")":/home/b/input.defconfig:ro
		ruyi-build-inner
	)
	docker run "${docker_args[@]}"
}

main "$@"
