docker:
    repo_url: openeuler/openeuler
    tag: "23.03"
basic_repo:
    repo_url: https://github.com/Liaoshihua/riscv-gnu-toolchain
    branch: backport-gcc-12
build_script:
    repo_url: https://github.com/GeassCore/ruyici.git
    branch: main
    path: gcc/openeuler/23.03/rv64ilp32/gcc.sh
