name: PR checks

on:
  pull_request:

jobs:
  shellcheck:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint with shellcheck
        run: ./scripts/lint-shell-scripts.sh
